version: '3'
services:
  ingest:
      image: "simpleflume"
      volumes:
        - "/Users/mk250075/dev/simpledemo/simpleflume/source:/opt/flume/source"
        - "/Users/mk250075/dev/simpledemo/simpleflume/target:/opt/flume/target"
  compute:
      image: "simplespark"
      volumes:
        - "/Users/mk250075/dev/simpledemo/simpleflume/target:/opt/spark/source"
