version: '3'
services:
  ingest:
      image: "simpleflume"
      volumes:
        - "/simpledockerintegration/simpleflume/source:/opt/flume/source"
        - "/simpledockerintegration/simpleflume/target:/opt/flume/target"
  compute:
      image: "simplespark"
      volumes:
        - "/simpledockerintegration/simpleflume/target:/opt/spark/source"
